trigger:
  branches:
    include:
      - master
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.6.0
      endpoint: github

variables:
  CONFIGURATION: Release
  VERBOSITY: Normal
  DOTNETVERSION: "2.2.300"
  DOTNET3VERSION: "3.0.100-preview6-012264"
  NUGETVERSION: "5.1.0"
  COVERAGE: "$(Agent.BuildDirectory)/c"
  ARTIFACTS: $(Build.ArtifactStagingDirectory)
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  CodeCovToken: '734b66b4-0bfd-45c8-9935-60d4a108de28'

jobs:
  - template: pipeline/nuke.yml@rsg
    parameters:
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      DotNetVersion: $(DotNetVersion)
      DotNet3Version: $(DotNet3Version)
      NuGetVersion: $(NuGetVersion)
